<?php

declare(strict_types=1);

/*
 * Build llms-full.txt from the files an agent needs, so it cannot drift from them.
 *
 * `php scripts/build-llms.php` writes it. `--check` exits non-zero when the committed
 * copy is stale, which is how CI keeps it honest.
 */

$root = dirname(__DIR__);

$read = static function (string $path) use ($root): string {
    $contents = file_get_contents($root.'/'.$path);

    if ($contents === false) {
        fwrite(STDERR, "Cannot read {$path}\n");
        exit(1);
    }

    return $contents;
};

$agents = $read('AGENTS.md');
$agents = mb_substr($agents, 0, mb_strpos($agents, '<!-- Everything below this line is generated by Laravel Boost.') ?: mb_strlen($agents));

$skill = (string) preg_replace('/\A---\R.*?\R---\R/s', '', $read('.ai/skills/saas-foundation/SKILL.md'));

$sections = [
    'README.md' => $read('README.md'),
    'AGENTS.md' => $agents,
    '.ai/skills/saas-foundation/SKILL.md' => $skill,
];

$output = "# Laravel SaaS Foundation, in full\n\nGenerated by scripts/build-llms.php from the files named below. Do not edit by hand.\n";

foreach ($sections as $path => $contents) {
    $output .= "\n---\n\nSource: {$path}\n\n".mb_trim($contents)."\n";
}

$target = $root.'/llms-full.txt';

if (in_array('--check', $argv, true)) {
    if (! is_file($target) || file_get_contents($target) !== $output) {
        fwrite(STDERR, "llms-full.txt is stale. Run: php scripts/build-llms.php\n");
        exit(1);
    }

    exit(0);
}

file_put_contents($target, $output);
